PRAGMA foreign_keys = ON;

-- ----------------------------------------------------------------------------
-- DEVICE REGISTRATION
-- ----------------------------------------------------------------------------

-- Single-use registration codes generated by admin
CREATE TABLE registration_codes
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    code       TEXT UNIQUE NOT NULL, -- High-entropy code (e.g., 32 char hex)
    created_at TEXT        NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_registration_codes_code ON registration_codes (code);

-- Single registered device (the partner's phone)
CREATE TABLE device
(
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    public_key      TEXT NOT NULL, -- Ed25519 public key (base64 or hex)
    key_fingerprint TEXT NOT NULL, -- SHA-256 hash of public key (base64 or hex)
    registered_at   TEXT NOT NULL DEFAULT (datetime('now')),
    last_seen_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ----------------------------------------------------------------------------
-- REVEALS
-- ----------------------------------------------------------------------------

CREATE TABLE reveals
(
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    order_index INTEGER NOT NULL, -- Explicit ordering (allows ties)
    title       TEXT    NOT NULL, -- Display name
    description TEXT,             -- Optional flavor text
    not_before  TEXT,             -- Can be null if it can only be revealed by a choice
    created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_reveals_order ON reveals (order_index);

-- ----------------------------------------------------------------------------
-- UNLOCKS (Gates)
-- ----------------------------------------------------------------------------

CREATE TABLE gates
(
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    reveal_id        INTEGER NOT NULL, -- Which reveal this gates
    unlock_order     INTEGER NOT NULL, -- Evaluation order within reveal (0-indexed)
    type             TEXT    NOT NULL, -- LOCATION | CODE | CHOICE

    -- LOCATION fields
    latitude         REAL,
    longitude        REAL,
    radius_meters    INTEGER,
    location_name    TEXT,

    -- CODE fields
    code_hash        TEXT,

    -- CHOICE fields
    choice_prompt    TEXT,
    chosen_option_id INTEGER,

    created_at       TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at       TEXT    NOT NULL DEFAULT (datetime('now')),
    unlocked_at      TEXT,

    FOREIGN KEY (reveal_id) REFERENCES reveals (id) ON DELETE CASCADE,
    FOREIGN KEY (chosen_option_id) REFERENCES choice_options (id) ON DELETE SET NULL,

    -- Enforce type-specific constraints
    CHECK (
        (type = 'LOCATION' AND latitude IS NOT NULL AND longitude IS NOT NULL AND radius_meters IS NOT NULL) OR
        (type = 'CODE' AND code_hash IS NOT NULL) OR
        (type = 'CHOICE' AND choice_prompt IS NOT NULL)
        )
);

CREATE INDEX idx_unlocks_reveal ON gates (reveal_id, unlock_order);

-- Choice options (only for CHOICE gates)
CREATE TABLE choice_options
(
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    gate_id      INTEGER NOT NULL,
    option_order INTEGER NOT NULL,
    label        TEXT    NOT NULL,

    reveal_id    INTEGER NOT NULL,

    created_at   TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at   TEXT    NOT NULL DEFAULT (datetime('now')),

    FOREIGN KEY (gate_id) REFERENCES gates (id) ON DELETE CASCADE,
    FOREIGN KEY (reveal_id) REFERENCES reveals (id) ON DELETE SET NULL,

    UNIQUE (gate_id, option_order)
);

-- ----------------------------------------------------------------------------
-- REWARDS
-- ----------------------------------------------------------------------------

CREATE TABLE rewards
(
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    reveal_id          INTEGER NOT NULL, -- Which reveal grants this
    type               TEXT    NOT NULL, -- CONTENT | FAVOUR
    title              TEXT    NOT NULL, -- Display name
    reward_order       INTEGER NOT NULL, -- Display order within reveal

    -- TYPE-SPECIFIC FIELDS

    -- CONTENT fields (also used for gift cards & experience tokens via HTML)
    content_html       TEXT,             -- Sanitized HTML (can include styled gift cards, etc.)
    content_media_url  TEXT,             -- Optional image/video/audio URL
    content_media_type TEXT,             -- MIME type

    -- FAVOUR fields
    give_favours       INTEGER NOT NULL DEFAULT 0,

    created_at         TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at         TEXT    NOT NULL DEFAULT (datetime('now')),
    unlocked_at        TEXT,

    FOREIGN KEY (reveal_id) REFERENCES reveals (id) ON DELETE CASCADE,

    -- Type-specific constraints
    CHECK (
        (type = 'CONTENT' AND content_html IS NOT NULL) OR
        (type = 'FAVOUR' AND give_favours > 0)
        )
);

CREATE INDEX idx_rewards_reveal ON rewards (reveal_id, reward_order);

-- -----------------------------------------------------------------------------
-- FAVOURS
-- -----------------------------------------------------------------------------
CREATE TABLE favour_count
(
    id            INTEGER PRIMARY KEY DEFAULT 0 CHECK ( id = 0 ),
    total_favours INTEGER NOT NULL    DEFAULT 0,
    created_at    TEXT    NOT NULL    DEFAULT (datetime('now')),
    updated_at    TEXT    NOT NULL    DEFAULT (datetime('now'))
);

CREATE TABLE favour_choice
(
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    label       TEXT    NOT NULL,
    description TEXT,
    can_message INTEGER NOT NULL DEFAULT 1, -- Whether user can message when requesting
    created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE favour_requests
(
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    favour_choice_id INTEGER NOT NULL,
    message          TEXT,
    requested_at     TEXT    NOT NULL DEFAULT (datetime('now')),
    fulfilled_at     TEXT,

    FOREIGN KEY (favour_choice_id) REFERENCES favour_choice (id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- ADMIN
-- ----------------------------------------------------------------------------

CREATE TABLE admin_login
(
    id            INTEGER PRIMARY KEY DEFAULT 0 CHECK ( id = 0 ),
    api_key       TEXT NOT NULL,
    created_at    TEXT NOT NULL       DEFAULT (datetime('now')),
    last_used    TEXT
);

-- ----------------------------------------------------------------------------
-- TRIGGERS
-- ----------------------------------------------------------------------------
CREATE TRIGGER trg_update_reveal_updated_at
AFTER UPDATE ON reveals
FOR EACH ROW
BEGIN
    UPDATE reveals SET updated_at = datetime('now') WHERE id = NEW.id;
END;

CREATE TRIGGER trg_update_gate_updated_at
AFTER UPDATE ON gates
FOR EACH ROW
BEGIN
    UPDATE reveals SET updated_at = datetime('now') WHERE id = NEW.reveal_id;
END;

CREATE TRIGGER trg_update_choice_option_updated_at
AFTER UPDATE ON choice_options
FOR EACH ROW
BEGIN
    UPDATE reveals SET updated_at = datetime('now') WHERE id = NEW.reveal_id;
END;

CREATE TRIGGER trg_update_reward_updated_at
AFTER UPDATE ON rewards
FOR EACH ROW
BEGIN
    UPDATE reveals SET updated_at = datetime('now') WHERE id = NEW.reveal_id;
END;

CREATE TRIGGER trg_update_favour_count_updated_at
AFTER UPDATE ON favour_count
FOR EACH ROW
BEGIN
    UPDATE favour_count SET updated_at = datetime('now') WHERE id = 0;
END;

CREATE TRIGGER trg_update_favour_choice_updated_at
AFTER UPDATE ON favour_choice
FOR EACH ROW
BEGIN
    UPDATE favour_choice SET updated_at = datetime('now') WHERE id = NEW.id;
END;