PRAGMA foreign_keys = ON;

-- ----------------------------------------------------------------------------
-- DEVICE REGISTRATION
-- ----------------------------------------------------------------------------

-- Single-use registration codes generated by admin
CREATE TABLE IF NOT EXISTS registration_codes
(
    id         INTEGER PRIMARY KEY  DEFAULT 1,
    code       TEXT UNIQUE NOT NULL, -- High-entropy code (e.g., 32 char hex)
    created_at DATETIME    NOT NULL DEFAULT (datetime('now')),
    expires_at DATETIME    NOT NULL  -- Expiration timestamp

        CHECK (id = 1)               -- Ensure only one row exists at a time
);

CREATE INDEX IF NOT EXISTS idx_registration_codes_code ON registration_codes (code);

-- Single registered device (the partner's phone)
CREATE TABLE IF NOT EXISTS device
(
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    token         TEXT     NOT NULL, -- High-entropy device token
    device_info   TEXT     NOT NULL,
    registered_at DATETIME NOT NULL DEFAULT (datetime('now')),
    last_seen_at  DATETIME NOT NULL DEFAULT (datetime('now')),
    expires_at    DATETIME NOT NULL
);

-- -----------------------------------------------------------------------------
-- GRAPH NODES AND EDGES
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS node (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,

    type        TEXT NOT NULL, -- E.G. START | LOCATION | CODE | CHOICE | REWARD

    title       TEXT,
    description TEXT,
    unlocked_at DATETIME,

    -- UI positioning for graph editor
    ui_pos_x    REAL,
    ui_pos_y    REAL,

    created_at  DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at  DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS edge (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    from_node_id INTEGER NOT NULL,
    to_node_id   INTEGER NOT NULL,

    choice_label    TEXT, -- For choice edges

    created_at   DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at   DATETIME NOT NULL DEFAULT (datetime('now')),

    FOREIGN KEY (from_node_id) REFERENCES node(id) ON DELETE CASCADE,
    FOREIGN KEY (to_node_id) REFERENCES node(id) ON DELETE CASCADE,

    UNIQUE (from_node_id, choice_label),
    CHECK (from_node_id != to_node_id)
);

CREATE TABLE IF NOT EXISTS node_start (
    node_id INTEGER PRIMARY KEY,
    starting_at DATETIME NOT NULL,

    viewport_x REAL,
    viewport_y REAL,
    viewport_zoom REAL,

    FOREIGN KEY (node_id) REFERENCES node(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS node_location_gate (
    node_id INTEGER PRIMARY KEY,

    latitude REAL NOT NULL,
    longitude REAL NOT NULL,
    radius_meters INTEGER NOT NULL,

    FOREIGN KEY (node_id) REFERENCES node(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS node_code_gate (
    node_id INTEGER PRIMARY KEY,

    code TEXT NOT NULL,

    FOREIGN KEY (node_id) REFERENCES node(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS node_reward (
    node_id INTEGER PRIMARY KEY,

    reward_type TEXT NOT NULL,

    content_html TEXT,
    content_media_type TEXT,

    give_favours INTEGER NOT NULL DEFAULT 0,

    FOREIGN KEY (node_id) REFERENCES node(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- FAVOURS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS favour_count
(
    id            INTEGER PRIMARY KEY DEFAULT 0 CHECK ( id = 0 ),
    total_favours INTEGER  NOT NULL   DEFAULT 0,
    created_at    DATETIME NOT NULL   DEFAULT (datetime('now')),
    updated_at    DATETIME NOT NULL   DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS favour_choice
(
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    label       TEXT     NOT NULL Unique,
    description TEXT,
    can_message INTEGER  NOT NULL DEFAULT 1, -- Whether user can message when requesting
    created_at  DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at  DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS favour_requests
(
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    favour_choice_id INTEGER  NOT NULL,
    message          TEXT,
    requested_at     DATETIME NOT NULL DEFAULT (datetime('now')),
    fulfilled_at     DATETIME,

    FOREIGN KEY (favour_choice_id) REFERENCES favour_choice (id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- TRIGGERS
-- ----------------------------------------------------------------------------
CREATE TRIGGER IF NOT EXISTS trg_update_favour_count_updated_at
    AFTER UPDATE
    ON favour_count
    FOR EACH ROW
BEGIN
    UPDATE favour_count SET updated_at = datetime('now') WHERE id = 0;
END;

CREATE TRIGGER IF NOT EXISTS trg_update_favour_choice_updated_at
    AFTER UPDATE
    ON favour_choice
    FOR EACH ROW
BEGIN
    UPDATE favour_choice SET updated_at = datetime('now') WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS trg_update_node_updated_at
    AFTER UPDATE
    ON node
    FOR EACH ROW
BEGIN
    UPDATE node SET updated_at = datetime('now') WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS trg_update_edge_updated_at
    AFTER UPDATE
    ON edge
    FOR EACH ROW
BEGIN
    UPDATE edge SET updated_at = datetime('now') WHERE id = NEW.id;
END;

-- ----------------------------------------------------------------------------
-- VIEWS
-- ----------------------------------------------------------------------------

CREATE VIEW IF NOT EXISTS node_full AS
SELECT
    n.id,
    n.type,
    n.title,
    n.description,
    n.ui_pos_x,
    n.ui_pos_y,
    n.created_at,
    n.updated_at,
    n.unlocked_at,

    ns.starting_at,
    ns.viewport_x,
    ns.viewport_y,
    ns.viewport_zoom,

    nlg.latitude,
    nlg.longitude,
    nlg.radius_meters,

    ncg.code,

    nr.reward_type,
    nr.content_html,
    nr.content_media_type,
    nr.give_favours
FROM node n
         LEFT JOIN node_start ns ON n.id = ns.node_id
         LEFT JOIN node_location_gate nlg ON n.id = nlg.node_id
         LEFT JOIN node_code_gate ncg ON n.id = ncg.node_id
         LEFT JOIN node_reward nr ON n.id = nr.node_id;