PRAGMA foreign_keys = ON;

-- ----------------------------------------------------------------------------
-- DEVICE REGISTRATION
-- ----------------------------------------------------------------------------

-- Single-use registration codes generated by admin
CREATE TABLE IF NOT EXISTS registration_codes
(
    id         INTEGER PRIMARY KEY  DEFAULT 1,
    code       TEXT UNIQUE NOT NULL, -- High-entropy code (e.g., 32 char hex)
    created_at DATETIME    NOT NULL DEFAULT (datetime('now')),
    expires_at DATETIME    NOT NULL  -- Expiration timestamp

        CHECK (id = 1)               -- Ensure only one row exists at a time
);

CREATE INDEX IF NOT EXISTS idx_registration_codes_code ON registration_codes (code);

-- Single registered device (the partner's phone)
CREATE TABLE IF NOT EXISTS device
(
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    token         TEXT     NOT NULL, -- High-entropy device token
    device_info   TEXT     NOT NULL,
    registered_at DATETIME NOT NULL DEFAULT (datetime('now')),
    last_seen_at  DATETIME NOT NULL DEFAULT (datetime('now')),
    expires_at    DATETIME NOT NULL
);

-- -----------------------------------------------------------------------------
-- GRAPH NODES AND EDGES
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS graph
(
    id            INTEGER PRIMARY KEY AUTOINCREMENT,

    title         TEXT     NOT NULL,
    description   TEXT,

    starting_at   DATETIME,

    viewport_x    REAL,
    viewport_y    REAL,
    viewport_zoom REAL,

    created_at    DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at    DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS node
(
    id          TEXT PRIMARY KEY, -- UUID v4
    graph_id    INTEGER  NOT NULL,

    type        TEXT     NOT NULL, -- E.G. START | LOCATION | CODE | CHOICE | REWARD

    title       TEXT,
    description TEXT,
    unlocked_at DATETIME,

    -- UI positioning for graph editor
    ui_pos_x    REAL,
    ui_pos_y    REAL,

    created_at  DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at  DATETIME NOT NULL DEFAULT (datetime('now')),

    FOREIGN KEY (graph_id) REFERENCES graph (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_one_start_per_graph
    ON node (graph_id)
    WHERE type = 'start';

CREATE TABLE IF NOT EXISTS edge
(
    id                  TEXT PRIMARY KEY, -- UUID v4

    graph_id            INTEGER  NOT NULL,
    source_node_id      TEXT  NOT NULL,
    destination_node_id TEXT  NOT NULL,

    choice_label        TEXT, -- For choice edges

    created_at          DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at          DATETIME NOT NULL DEFAULT (datetime('now')),

    FOREIGN KEY (graph_id) REFERENCES graph (id) ON DELETE CASCADE,
    FOREIGN KEY (source_node_id) REFERENCES node (id) ON DELETE CASCADE,
    FOREIGN KEY (destination_node_id) REFERENCES node (id) ON DELETE CASCADE,

    UNIQUE (source_node_id, choice_label),
    CHECK (source_node_id != destination_node_id)
);

CREATE TABLE IF NOT EXISTS node_location_gate
(
    node_id       TEXT PRIMARY KEY,

    latitude      REAL    NOT NULL,
    longitude     REAL    NOT NULL,
    radius_meters INTEGER NOT NULL,

    FOREIGN KEY (node_id) REFERENCES node (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS node_manual_gate
(
	node_id TEXT PRIMARY KEY,

	instructions TEXT NOT NULL,
	unlocked_at DATETIME, -- when the admin manually marked it as unlocked

	FOREIGN KEY (node_id) REFERENCES node (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS node_code_gate
(
    node_id TEXT PRIMARY KEY,

    code    TEXT NOT NULL,

    FOREIGN KEY (node_id) REFERENCES node (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS node_reward
(
    node_id            TEXT PRIMARY KEY,

    reward_type        TEXT    NOT NULL,

    content_html       TEXT,
    content_media_type TEXT,

    give_favours       INTEGER NOT NULL DEFAULT 0,

    FOREIGN KEY (node_id) REFERENCES node (id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- FAVOURS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS favour_count
(
    id            INTEGER PRIMARY KEY DEFAULT 0 CHECK ( id = 0 ),
    total_favours INTEGER  NOT NULL   DEFAULT 0,
    created_at    DATETIME NOT NULL   DEFAULT (datetime('now')),
    updated_at    DATETIME NOT NULL   DEFAULT (datetime('now'))
);
INSERT OR IGNORE INTO favour_count (id) VALUES (0);

CREATE TABLE IF NOT EXISTS favour_choice
(
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    label       TEXT     NOT NULL Unique,
    description TEXT,
    cost        INTEGER  NOT NULL DEFAULT 1,
    can_message BOOLEAN  NOT NULL DEFAULT FALSE, -- Whether user can message when requesting
    created_at  DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at  DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS favour_requests
(
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    favour_choice_id INTEGER  NOT NULL,
    message          TEXT,
    requested_at     DATETIME NOT NULL DEFAULT (datetime('now')),
    fulfilled_at     DATETIME,

    FOREIGN KEY (favour_choice_id) REFERENCES favour_choice (id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- TRIGGERS
-- ----------------------------------------------------------------------------
CREATE TRIGGER IF NOT EXISTS trg_update_favour_count_updated_at
    AFTER UPDATE
    ON favour_count
    FOR EACH ROW
BEGIN
    UPDATE favour_count SET updated_at = datetime('now') WHERE id = 0;
END;

CREATE TRIGGER IF NOT EXISTS trg_update_favour_choice_updated_at
    AFTER UPDATE
    ON favour_choice
    FOR EACH ROW
BEGIN
    UPDATE favour_choice SET updated_at = datetime('now') WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS trg_update_node_updated_at
    AFTER UPDATE
    ON node
    FOR EACH ROW
BEGIN
    UPDATE node SET updated_at = datetime('now') WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS trg_update_edge_updated_at
    AFTER UPDATE
    ON edge
    FOR EACH ROW
BEGIN
    UPDATE edge SET updated_at = datetime('now') WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS trg_update_graph_updated_at
    AFTER UPDATE
    ON graph
    FOR EACH ROW
BEGIN
    UPDATE graph SET updated_at = datetime('now') WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS node_start_always_unlocked_insert
	BEFORE INSERT ON node
	FOR EACH ROW
	WHEN NEW.type = 'START'
BEGIN
	SELECT
		CASE
			WHEN NEW.unlocked_at IS NULL
				THEN
				NEW.unlocked_at = datetime('now')
			END;
END;

CREATE TRIGGER IF NOT EXISTS node_start_always_unlocked_update
	BEFORE UPDATE OF type, unlocked_at ON node
	FOR EACH ROW
	WHEN NEW.type = 'START'
BEGIN
	SELECT
		CASE
			WHEN NEW.unlocked_at IS NULL
				THEN
				NEW.unlocked_at = datetime('now')
			END;
END;

-- ----------------------------------------------------------------------------
-- VIEWS
-- ----------------------------------------------------------------------------

CREATE VIEW IF NOT EXISTS node_full AS
SELECT n.id,
       n.graph_id,
       n.type,
       n.title,
       n.description,
       n.ui_pos_x,
       n.ui_pos_y,
       n.created_at,
       n.updated_at,
       n.unlocked_at,

       CASE n.type
           WHEN 'location' THEN json_object(
                   'latitude', nlg.latitude,
                   'longitude', nlg.longitude,
                   'radius_m', nlg.radius_meters
           )
           WHEN 'code' THEN json_object(
                   'code', ncg.code
		   )
           WHEN 'manual' THEN json_object(
				   'instructions', nmg.instructions,
				   'unlocked_at', nmg.unlocked_at
		   )
           WHEN 'reward' THEN json_object(
                   'reward_type', nr.reward_type,
                   'content_html', nr.content_html,
                   'content_media_type', nr.content_media_type,
                   'give_favours', nr.give_favours
                              )
           ELSE json('{}')
           END AS data_json

FROM node n
         LEFT JOIN node_location_gate nlg ON n.id = nlg.node_id
         LEFT JOIN node_code_gate ncg ON n.id = ncg.node_id
         LEFT JOIN node_reward nr ON n.id = nr.node_id
		 LEFT JOIN node_manual_gate nmg ON n.id = nmg.node_id;
